on: [push]

name: CI

jobs:
  build_and_test_ubuntu:
    name: Build ubuntu
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release --all-features
      - name: Archive linux artifacts
        uses: actions/upload-artifact@v2
        with:
          name: linux-target
          path: target
  build_and_test_mac:
    name: Build mac
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release --all-features
      - name: Archive mac artifacts
        uses: actions/upload-artifact@v2
        with:
          name: mac-target
          path: target
